### ISSUE TITLE
Syntax highlighting and markdown preview

### ISSUE THREAD

**Issue by mchernosky** [jonmagic/nvatom-package#3]
Hi,

Just wanted to point out for anyone that the "file scope" of the created notes is `source.gfm.nvatom`, so if you want to use the [spell-check](https://github.com/atom/spell-check) or [markdown-preview](https://github.com/atom/markdown-preview) packages, then you need to add `source.gfm.nvatom` to the **Grammars** sections in the settings for those packages.

**Comment by mchernosky** [comment]
Oh also, I'm loving this package. Thanks for it!

**Comment by jonmagic** [comment]
I'm using https://atom.io/packages/atom-notes these days so will likely archive this project.
